/* Read-only teaching layer over the existing dashboard. It never advances physics. */
export function enhanceElectricalPath(base){
 const $=id=>document.getElementById(id),state=window.dashboardState;
 const link=document.createElement('link');link.rel='stylesheet';link.href='electrical-path.css';document.head.append(link);
 const bridge=$('bridge-instrument'),sensor=document.querySelector('.sensor-instrument'),presets=document.querySelector('.presets');
 if(!bridge||!sensor||!presets)return base;

 const lab=document.createElement('section');lab.id='switching-lab';lab.className='instrument switching-lab';lab.setAttribute('aria-label','Synchronized electrical control path');
 lab.innerHTML=`<div class="switching-head"><div><span class="eyebrow">FOLLOW ONE ELECTRICAL SAMPLE</span><h3>FOC → SVPWM → PWM ownership → inverter → current feedback</h3></div><div class="time-scale-note"><b>Live joint</b> 20 kHz averaged control · <b>micro inspector</b> one native 50 μs switching reconstruction</div></div><div class="electrical-flow-grid"><section class="electrical-stage foc-stage"><span class="stage-kicker">01 / FOC OUTPUT</span><h4>dq voltage → stationary αβ</h4><div class="electrical-values"><output id="electrical-iq">Iq* / Iq —</output><output id="electrical-vdq">Vd / Vq —</output><output id="electrical-alphabeta">Vα / Vβ —</output></div><svg class="mini-transform" viewBox="0 0 240 76" aria-label="Inverse Park transform"><rect x="8" y="18" width="62" height="40" rx="5"/><path d="M70 38H112"/><rect x="112" y="18" width="78" height="40" rx="5"/><path d="M190 38H232"/><text x="39" y="34">Vd,Vq</text><text x="39" y="49">rotating</text><text x="151" y="34">Inv. Park</text><text x="151" y="49">θe</text><text x="215" y="34">αβ</text></svg></section></div>`;
 presets.before(lab);const grid=lab.querySelector('.electrical-flow-grid');grid.append(bridge,sensor);sensor.classList.add('electrical-sensor-stage');

 const vector=$('vector-diagram');
 if(vector){
  vector.setAttribute('viewBox','0 0 120 104');
  const ns='http://www.w3.org/2000/svg',sectorGroup=document.createElementNS(ns,'g');sectorGroup.classList.add('svpwm-sectors');
  const pts=[['1','60,52 106,52 83,12'],['2','60,52 83,12 37,12'],['3','60,52 37,12 14,52'],['4','60,52 14,52 37,92'],['5','60,52 37,92 83,92'],['6','60,52 83,92 106,52']];
  for(const [n,p] of pts){const path=document.createElementNS(ns,'polygon');path.setAttribute('points',p);path.dataset.sector=n;path.classList.add('svpwm-sector');sectorGroup.append(path);}
  vector.prepend(sectorGroup);vector.insertAdjacentHTML('beforeend','<g class="svpwm-labels"><text x="112" y="55">V1</text><text x="84" y="9">V2</text><text x="32" y="9">V3</text><text x="7" y="55">V4</text><text x="32" y="101">V5</text><text x="84" y="101">V6</text></g>');
  const details=document.createElement('div');details.className='svpwm-details';details.innerHTML='<output id="svpwm-sector">Sector —</output><output id="svpwm-dwell">active dwells — · zero dwell —</output><div class="duty-pills"><span>Da <b id="duty-a">—</b></span><span>Db <b id="duty-b">—</b></span><span>Dc <b id="duty-c">—</b></span></div>';
  vector.insertAdjacentElement('afterend',details);
 }

 const owner=document.createElement('div');owner.className='ownership-panel';owner.innerHTML=`<div class="stage-title-row"><h4 id="pwm-owner-title">6PWM · MCU owns six commands</h4><output id="ownership-mode-note">same 3-phase / six-switch bridge</output></div><div class="ownership-flow" id="pwm-command-source" data-mode="6"><div class="owner-box" id="ownership-mcu"><b>MCU timer</b><div class="command-chips six"><span>AH</span><span>AL</span><span>BH</span><span>BL</span><span>CH</span><span>CL</span></div><div class="command-chips three"><span>PWM A</span><span>PWM B</span><span>PWM C</span></div></div><span class="owner-arrow">→</span><div class="owner-box" id="ownership-driver"><b>Gate driver</b><small id="ownership-driver-role">level shift + protection</small></div><span class="owner-arrow">→</span><div class="owner-box"><b>AH/AL · BH/BL · CH/CL</b><small>same six MOSFETs in both modes</small></div></div>`;
 const circuit=$('bridge-circuit');circuit?.insertAdjacentElement('beforebegin',owner);
 const selected=document.createElement('div');selected.className='selected-electrical-values';selected.innerHTML='<output id="selected-gates">Gates —</output><output id="selected-voltage">Va/Vb/Vc —</output>';circuit?.insertAdjacentElement('afterend',selected);
 const gate=$('gate-scope');if(gate){gate.hidden=true;const pair=document.createElement('div');pair.className='micro-scope-pair';pair.innerHTML='<div class="micro-scope"><div class="micro-caption"><b id="gate-rich-title">Six effective gates</b><small id="gate-rich-note">AH / AL / BH / BL / CH / CL</small></div><canvas id="gate-scope-rich" aria-label="Selected PWM requests or six effective gate commands"></canvas></div><div class="micro-scope"><div class="micro-caption"><b>Phase-neutral voltage</b><small>Va / Vb / Vc · same selected time</small></div><canvas id="voltage-scope" aria-label="Native reconstructed phase-neutral voltages"></canvas></div>';gate.insertAdjacentElement('afterend',pair);}
 const sensorSvg=sensor.querySelector('svg');if(sensorSvg){const read=document.createElement('div');read.className='electrical-values sensor-readouts';read.innerHTML='<output id="sensor-true">ia true —</output><output id="sensor-analog">ia analog —</output><output id="sensor-adc">ia ADC —</output>';sensorSvg.insertAdjacentElement('afterend',read);}

 function ownership(){const mode3=$('pwm-interface').value==='3',src=$('pwm-command-source');src.dataset.mode=mode3?'3':'6';$('pwm-owner-title').textContent=mode3?'3PWM · MCU sends three duty requests':'6PWM · MCU owns six gate commands';$('ownership-driver-role').textContent=mode3?'complementary PWM + dead-time':'level shift + protection';$('ownership-mode-note').textContent=mode3?'driver derives six gates':'timer exposes all six gates';}
 $('pwm-interface').addEventListener('change',ownership);ownership();

 function microPlot(canvas,rows,cols,us,{logic=false,labels=[]}={}){if(!canvas||!rows?.length)return;const rect=canvas.getBoundingClientRect();if(rect.width<1)return;const palette=['#5ce4bb','#ffc971','#6aaeff','#dd90c5','#70d7f0','#f38ca6'],dpr=Math.min(devicePixelRatio,2),w=rect.width,h=rect.height,l=logic?30:34,r=8,t=12,b=18,lane=1.35,targetW=Math.round(w*dpr),targetH=Math.round(h*dpr);if(canvas.width!==targetW)canvas.width=targetW;if(canvas.height!==targetH)canvas.height=targetH;const c=canvas.getContext('2d');c.setTransform(dpr,0,0,dpr,0,0);c.clearRect(0,0,w,h);const vals=rows.flatMap(a=>cols.map(k=>a[k])).filter(Number.isFinite),lo=logic?-.15:Math.min(...vals),hi=logic?(cols.length-1)*lane+.8:Math.max(...vals),pad=logic?0:Math.max(.1,(hi-lo)*.08),y0=lo-pad,y1=hi+pad,X=x=>l+x/50*(w-l-r),Y=y=>h-b-(y-y0)/(y1-y0)*(h-t-b),V=(a,k,j)=>logic?(cols.length-1-j)*lane+.58*a[k]:a[k];c.strokeStyle='#29414f';c.strokeRect(l,t,w-l-r,h-t-b);cols.forEach((k,j)=>{c.strokeStyle=palette[j%palette.length];c.lineWidth=1.35;c.beginPath();let prev=null;rows.forEach(a=>{const x=X(a[0]*1e6),y=Y(V(a,k,j));if(prev&&logic)c.lineTo(x,Y(V(prev,k,j)));if(prev)c.lineTo(x,y);else c.moveTo(x,y);prev=a});c.stroke();if(logic){c.fillStyle=palette[j%palette.length];c.font='8px ui-monospace,monospace';c.fillText(labels[j]||String(j+1),2,Y((cols.length-1-j)*lane+.28)+3);}});c.strokeStyle='#fff';c.setLineDash([3,2]);c.beginPath();c.moveTo(X(us),t);c.lineTo(X(us),h-b);c.stroke();canvas.dataset.samples=String(rows.length);canvas.dataset.cursorUs=Number(us).toFixed(4);canvas.dataset.series=String(cols.length);canvas.dataset.layout=logic?'lanes':'overlay';}
 function sampleAt(rows,us){const t=us*1e-6;let s=rows[0];for(const a of rows){if(a[0]>t)break;s=a;}return s;}
 function updateTeaching(force=false){const now=performance.now();if(!force&&now-(state.electricalTeachingDrawnAt||0)<100)return;state.electricalTeachingDrawnAt=now;const h=state.history;if(!h?.length)return;const {r,s}=h.at(-1),theta=s[28],vd=s[4],vq=s[5],co=Math.cos(theta),si=Math.sin(theta),alpha=co*vd-si*vq,beta=si*vd+co*vq,duty=r.slice(14,17),angle=(Math.atan2(beta,alpha)+2*Math.PI)%(2*Math.PI),sector=Math.min(6,Math.floor(angle/(Math.PI/3))+1),vbus=Math.max(1e-9,r[7]),mag=Math.hypot(alpha,beta),max=2*vbus/3,scaleLimit=mag>max ? .98*max/mag : 1,sc=46/max*scaleLimit;
  $('electrical-iq').textContent=`Iq* ${r[5].toFixed(2)} A · Iq ${s[3].toFixed(2)} A`;$('electrical-vdq').textContent=`Vd ${vd.toFixed(2)} V · Vq ${vq.toFixed(2)} V`;$('electrical-alphabeta').textContent=`Vα ${alpha.toFixed(2)} V · Vβ ${beta.toFixed(2)} V · θe ${(theta*180/Math.PI).toFixed(1)}°`;
  const line=$('duty-vector');line?.setAttribute('d',`M60 52L${60+alpha*sc} ${52-beta*sc}`);document.querySelectorAll('.svpwm-sector').forEach(e=>e.classList.toggle('active',+e.dataset.sector===sector));$('svpwm-sector').textContent=`Sector ${sector} · V${sector}/V${sector===6?1:sector+1}`;const q=[...duty].sort((a,b)=>a-b),t1=(q[2]-q[1])*50,t2=(q[1]-q[0])*50,t0=Math.max(0,(1-q[2]+q[0])*50);$('svpwm-dwell').textContent=`active ${t1.toFixed(2)} / ${t2.toFixed(2)} μs · zero ${t0.toFixed(2)} μs`;['a','b','c'].forEach((n,k)=>$('duty-'+n).textContent=duty[k].toFixed(3));
  $('sensor-true').textContent=`ia true ${s[11].toFixed(3)} A`;$('sensor-analog').textContent=`ia analog ${s[17].toFixed(3)} A`;$('sensor-adc').textContent=`ia ADC ${s[8].toFixed(3)} A · age ${(s[6]*1e6).toFixed(0)} μs`;ownership();
  const rows=state.wave?.rows;if(rows?.length){const us=state.pwmPhaseUs??+$('pwm-phase').value,smp=sampleAt(rows,us),mode3=$('pwm-interface').value==='3',gateCols=mode3?[1,2,3]:[4,5,6,7,8,9],gateLabels=mode3?['A','B','C']:['AH','AL','BH','BL','CH','CL'];$('gate-rich-title').textContent=mode3?'Three PWM requests':'Six effective gates';$('gate-rich-note').textContent=mode3?'PWM A / PWM B / PWM C':'AH / AL / BH / BL / CH / CL';microPlot($('gate-scope-rich'),rows,gateCols,us,{logic:true,labels:gateLabels});microPlot($('voltage-scope'),rows,[14,15,16],us);$('selected-gates').textContent=['AH','AL','BH','BL','CH','CL'].map((n,k)=>`${n} ${smp[4+k]?'ON':'off'}`).join(' · ');$('selected-voltage').textContent=`Va ${smp[14].toFixed(1)} · Vb ${smp[15].toFixed(1)} · Vc ${smp[16].toFixed(1)} V`;}
 }
 const timer=setInterval(()=>{if(!document.hidden)updateTeaching(true)},220);state.electricalTeachingTimer=timer;
 const wrapped={...base,ingest(packet){base.ingest(packet)},update(force){base.update(force);updateTeaching(force)}};updateTeaching(true);return wrapped;
}
